name: run behave-test-steps regression tests
on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]
env:
  OPENJDK_CONTAINER_SOURCE_TAG: ubi9-openjdk-containers-1.18
  OPENJDK_CONTAINER:            ubi9/openjdk-17-runtime
  OPENJDK_CONTAINER_VERSION:    1.18
  OPENJDK_CONTAINER_DESCRIPTOR: ubi9-openjdk-17-runtime.yaml
jobs:
  openjdkci:
    name: behave-test-steps regression tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: fetch and tag openjdk runtime image
        run: |
          docker pull registry.access.redhat.com/${{ env.OPENJDK_CONTAINER }}:${{ env.OPENJDK_CONTAINER_VERSION }}
          docker tag  registry.access.redhat.com/${{ env.OPENJDK_CONTAINER }}:${{ env.OPENJDK_CONTAINER_VERSION }} \
            ${{ env.OPENJDK_CONTAINER }}:${{ env.OPENJDK_CONTAINER_VERSION }}

      - name: Install CEKit
        uses: rigazilla/actions-setup-cekit@fix-venv

# even though we don't run any S2I tests for the runtime images, the test suite
# will fail to start if the s2i binary is not present.
      - name: mock s2i binary
        run: sudo ln -s /usr/bin/echo /usr/bin/s2i

      - name: Run behave tests
        run: |
          STEPSDIR=$(pwd)
          git tag v1 # cekit hard-codes using ref v1
          cd test
          # enable our own scenarios. See #66 for context.
          for f in tests/features/*disabled; do mv "$f" "${f/.disabled/}"; done
          cekit -v test behave --steps-url file://$STEPSDIR
